Add go-yasunori
times-yasunori/awesome-yasunori pull request #144
Opened 2024-10-29 08:57 UTC by conao3

go yasunori~

2024-10-29 12:14 UTC, tomoya requested changes
no yasunori~

2024-10-29 12:14 UTC, tomoya commented on packages/go-yasunori/README.md
> +# clojure-yasunori
clojure のままになってる

2024-10-29 12:46 UTC, conao3 commented on packages/go-yasunori/README.md
> +# clojure-yasunori
Nice no yasunori! go yasunoriするように修正しました~

2024-10-30 02:26 UTC, tomoya approved these changes
go yasunori~

2024-10-30 02:26 UTC, merged